### ISSUE TITLE
Erros no Repositório

### ISSUE THREAD

**Issue by LeonardAugusto** [roscibely/algorithms-and-data-structure#142]
No repositório do link anexado, há dois erros:
1) No item "Função realloc" está escrito como "Funçãp realloc"
2) Duas imagens colocadas não estão carregando.
https://github.com/roscibely/algorithms-and-data-structure/tree/main/root/vectors

**Comment by roscibely** [comment]
@LeonardAugusto você pode fazer o fix e abrir o pull request?

**Comment by roscibely** [comment]
@JhoanDev

**Comment by JhoanDev** [comment]
Resolvido! @roscibely
